### ISSUE TITLE
Question Regarding CAMPAIGNER/AGENT/FACILITATOR Labels

### ISSUE THREAD

**Issue by miguelfrndzdeusto** [dkorenci/pan-clef-2024-oppositional#2]
We are currently working on the Oppositional Analysis task but we are not sure about the difference between the labels: `Campaigner`, `Agent`, and `Facilitator`. Could you please provide some insight into how these categories were assigned?

**Comment by dkorenci** [comment]
check the newly added .pdf file with a conceptual overview
